apiVersion: v1
kind: Pod
metadata:
  name: simon-game-pod
  labels:
    app: simon-game-dev
spec:
  containers:
    - name: simon-game-container
      image: emmanueladb/simon-game:dev
      imagePullPolicy: Always
      ports:
        - containerPort: 80
    # - name: counter-sidecar
    #   image: busybox:1.34
    #   command: [ "sh", "-c", 'while true; do echo "$i  $(date)"; i=$((i+1)); sleep 1; done' ]
